apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wolfgang-rsync-upload-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wolfgang-rsyncd-upload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wolfgang-rsyncd-upload
  template:
    metadata:
      labels:
        app: wolfgang-rsyncd-upload
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                run-together: rsync-and-jellyfin
            topologyKey: kubernetes.io/hostname
      # securityContext:
      #   fsGroup: 1001 # GID of rsyncgroup
      containers:
        - name: rsync-daemon
          image: ezzieyguywuf/ubuntu-rsync:latest
          command: ["/usr/bin/rsync"]
          args:
            - "--verbose"
            - "--daemon"
            - "--address=0.0.0.0"
            - "--config=/etc/rsyncd.conf"
            - "--no-detach"
            - "--port=8730"
          ports:
            - containerPort: 8730
              name: rsync
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
            capabilities:
              drop: ["ALL"]
              add: ["CAP_CHOWN", "CAP_SETGID", "CAP_SETUID"]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: wolfgang-rsync-upload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wolfgang-rsync-public-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 873
      targetPort: 8730
  selector:
    app: wolfgang-rsyncd-upload
